#!/usr/bin/env R

# script to process rsheet files
# Processes rsheet files generated by Recount Methylation server
# Arguments
# 1. timestamp (str): an NTP timestamp

require(minfi)

#-----------
# Functions
#-----------
get_latest_rsheet <- function(sheetspath="./recount-methylation-files/sheetfiles"){
  # get latest files sheet
  sheet_fn = list.files(sheetspath)
  sheet_fn = sheet_fn[grep(".*rsheet$", sheet_fn)]
  timestamps = strsplit(sheet_fn,"\\.")
  ts = c()
  for(i in 1:length(timestamps)){ts = c(ts,timestamps[[i]][1])}
  sheet_latest = sheet_fn[which(ts==max(ts))]
  sheetidat <- read.table(paste0(sheetspath,"/",sheet_latest), 
                          sep = " ", stringsAsFactors = F, header = T)
  return(sheetidat)
}

get_minfi_arraysizedf <- function(sheetidat){
  stdout <- vector('character')
  con    <- textConnection('stdout', 'wr', local = TRUE)
  sink(con)
  read.metharray.exp(targets=sheetidat, force=TRUE)
  sink()
  close(con)
  so <- stdout[3:length(stdout)]
  arrayinfo = so[(grep("array",so)+1):(grep("size",so)-1)]
  arraybasenames = gsub(" .*","",arrayinfo)
  platforminfo = gsub('\"',"",gsub(".* ","",arrayinfo))
  sizeinfo = so[(grep("size",so)+1):length(so)]
  arraysizes = as.numeric(gsub('(\"| )','',gsub('.* \"','',sizeinfo)))
  dfplatforms = data.frame(basename = arraybasenames, 
                           platform = platforminfo,
                           arraysizes = arraysizes,
                           stringsAsFactors = F)
  return(dfplatforms)
}

append_arraysizes <- function(timestamp,sheetidat,dfplatforms){
  # Append and save the array size info
  sheetbn <- gsub(".*/","",sheetidat$Basename)
  dfplatforms <- dfplatforms[order(match(dfplatforms$basename,sheetbn)),]
  if(identical(sheetbn,dfplatforms$basename)){
    sheetidat$arraysize <- dfplatforms$arraysizes
    sheetidat$platformdet <- dfplatforms$platform
    # save the file with appended timestamp
    save(sheetidat,file=paste0(timestamp,".sheetidatsize.rda"))
    return(1)
  } else{
    return(0)
  }
}

get_latest_sizessheet <- function(sheetspath="./recount-methylation-files/sheetfiles"){
  sheet_fn = list.files(sheetspath)
  sheet_fn = sheet_fn[grep(".*sheetidatsize.rda$", sheet_fn)]
  timestamps = strsplit(sheet_fn,"\\.")
  ts = c()
  for(i in 1:length(timestamps)){ts = c(ts,timestamps[[i]][1])}
  sheetidat_latest = sheet_fn[which(ts==max(ts))]
  return(sheetidat_latest)
}

readexp_sizefilt <- function(timestamp,platformfilt="IlluminaHumanMethylation450k"){
  sheetidat <- get_latest_sizessheet()
  sheetidat <- sheetidat[sheetidat$platformdet==platformfilt,]
  if(nrow(sheetidat)>0){
    mexp <- read.metharray.exp(targets=sheetidatfilt,force=TRUE)
    save(mexp,file=paste0(timestamp,".mexp.rda"))
    return(1)
  } else{
    message("No files meet sheetidat filter criteria! Returning...")
    return(0)
  }
}

#--------
# Script
#--------
sheetprocess <- function(timestamp){
  sheetidat <- get_latest_rsheet()
  dfplatforms <- get_minfi_arraysizedf(sheetidat=sheetidat)
  aastat <- append_arraysizes(timestamp=timestamp,sheetidat=sheetidat,dfplatforms=dbplatforms)
  if(aastat==1){
    rsfstat <- readexp_sizefilt(timestamp=timestamp)
    if(rfstat==1){
      message("Successfully read idats using size filter! Returning...")
      return(1)
    } else{
      message("Error reading in idats on size filter. Returning...")
      return(0)
    }
  } else{
    message("Erorr appending array size information to sheetidat! Returning...")
    return(0)
  }
  # Get platforms and array sizes
  dfplatforms <- get_minfi_arraysizedf()
  # Read in the sizes file and filter on platform/size
}

suppressWarnings(sheetprocess(timestamp = commandArgs(T)[1]))